---
# 11pm --> late_evening
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_period_lateevening"
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.period
      option: "late_evening"
