---
# Sun sets --> Evening
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_period_evening"
trigger:
  - platform: sun
    event: sunset
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.period
      option: "evening"
