---
# 1pm --> Afternoon
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_period_afternoon"
trigger:
  - platform: time
    at: "13:00:00"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.period
      option: "afternoon"
