---
# Anything playing on Living TV --> Turn off the lights
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "media_player_shield_playing"
trigger:
  - platform: state
    entity_id: media_player.nvidia_shield_cast
    to: "playing"
action:
  - delay:
      seconds: 1 # Let media_player_shield_playing_save save stuff
  - service: script.light_living_off
