---
# Anything playing on Living TV --> Turn off the lights
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "media_player_shield_playing_save"
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: media_player.nvidia_shield_cast
    to: "playing"
action:
  - service: system_log.write
    data:
      message: "Saving living_before_playing scene"
      logger: "media_player_shield_playing_save"
  - service: scene.create
    data:
      scene_id: living_before_playing
      snapshot_entities:
        - light.hall
        - light.cuisine
        - light.plan_de_travail
        - light.bar
        - light.bar_tablette
        - light.lampe_noire
        - light.hall_console
        - switch.guirlande_du_living
  - delay:
      seconds: 1
  - service: script.light_living_off
  # Block any new execution of this automation while Shield has not been paused for 15seconds
  - wait_template: "{{ not is_state('media_player.nvidia_shield_cast', 'playing') }}"
  - service: system_log.write
    data:
      message: "Execution has been unpaused, player is no longer playing"
      logger: "media_player_shield_playing_save"
  - delay:
      seconds: 15
