---
# hotte_remote_on
# Press off on hotte Remote --> Turn off hotte
#
# https://www.home-assistant.io/integrations/deconz/#remote-control-devices
#

alias: hotte_remote_on
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: interrupteur_hotte
      event: 1002
action:
  - service: switch.turn_on
    entity_id: switch.hotte
