---
# alarm_arming
# Action when the alarm is arming
#
# https://www.home-assistant.io/integrations/manual/
#

alias: alarm_arming
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarme
    to: "armed"
action:
  - service: script.turn_off
    entity_id: script.tts_alarm_arming
  - service: script.tts_alarm_armed
