default_config:

homeassistant:
  name: !secret name

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  unit_system: metric
  time_zone: Europe/Brussels

device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
