---
# Actions performed when any window is opened
#
alias: "windows_open"
trigger:
  - platform: state
    entity_id: group.windows
    to: "on"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chaudiere_blocker
