---
# Reset input_select radio & player after a while
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_radio_reset"
mode: restart
trigger:
  - platform: state
    entity_id: input_select.radio_station, input_select.radio_player
action:
  - delay:
      seconds: 15
  - service: input_select.select_option
    data:
      entity_id: input_select.radio_station
      option: "Choisir..."
  - service: input_select.radio_player
    data:
      entity_id: input_select.presence
      option: "Choisir..."
