# Toggle Switch Living_hall when toggling the Light
#
alias: switch_living_hall_off
trigger:
  - platform: state
    entity_id: light.hall
    to: "off"
action:
  - service: homeassistant.turn_off
    entity_id: switch.living_hall
