# Toggle Hall when pressing right in-wall switch in Living
#
alias: switch_living_hall_off
trigger:
  - platform: state
    entity_id: switch.living_hall
    to: "off"
action:
  - service: homeassistant.turn_off
    entity_id: light.hall
