---
# Turn climate away when receiving push notification event

alias: "climate_event_away"
trigger:
  - platform: event
    event_type: "ios.notification_action_fired"
    event_data:
      actionName: CLIMATE_AWAY
action:
  # Turn heating away
  - service: script.climate_away
  # Notify
  - service: script.push_processing
    data_template:
      title: "Thermostat 🌡️"
      message: "Le thermostat est réglé sur {{ states.climate.living.attributes.temperature | int}}°."
      identifier: "climate_main"
      category: "climate_home_on_trip"
