# Toggle plan_de_travail using bar switch
#
alias: switch_bar_double_toggle
trigger:
  - platform: state
    entity_id: sensor.bar_switch_action
    attribute: state_left
action:
  - service: homeassistant.toggle
    entity_id: light.bar
