# Toggle plan_de_travail using bar switch
#
alias: switch_bar_double_toggle
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      platform: event
      event_type: deconz_event
      event_data:
        id: bar_switch
        event: 1004
action:
  - service: homeassistant.toggle
    entity_id: light.plan_de_travail
