# Toggle plan_de_travail using bar switch
#
alias: switch_bar_left
trigger:
  - platform: state
    entity_id: sensor.bar_switch_click
    to: "left_single"
action:
  - service: homeassistant.toggle
    entity_id: light.cuisine_1
