---
# Leaving for 15 minutes --> Away
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_presence_away"
trigger:
  - platform: state
    entity_id: input_select.presence
    to: "leaving"
    for:
      seconds: 15
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: "away"
