---
# Coming_home for 15 minutes --> Home
#
# https://www.home-assistant.io/integrations/input_select/
#
alias: "input_select_presence_home"
trigger:
  - platform: state
    entity_id: input_select.presence
    to: "coming_home"
    for:
      seconds: 15
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: "home"
