---
# When we no longer have high humidity
# and extracteur is not running because of timer
# --> Switch off extracteur_d_air
#
alias: extracteur_humidity_off
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_floating_humidity
    below: 70
condition:
  - condition: state
    entity_id: timer.extracteur_d_air
    state: "active"
action:
  - service: switch.turn_off
    entity_id: switch.extracteur_d_air
