---
# When extracteur_d_air_salle_de_bain is turned off
# --> Cancel timer
#
alias: switch_timer_extracteur_d_air_salle_de_bain_off
trigger:
  - platform: state
    entity_id: switch.extracteur_d_air_salle_de_bain
    to: "off"
action:
  - service: timer.cancel
    entity_id: timer.extracteur_d_air_salle_de_bain
