---
# When extracteur_d_air is turned off
# --> Cancel timer
#
alias: switch_timer_extracteur_d_air_off
trigger:
  - platform: state
    entity_id: switch.extracteur_d_air
    to: "off"
action:
  - service: timer.cancel
    entity_id: timer.extracteur_d_air
