---
# salle_de_bain_remote_long
# Press long on bathroom_switch --> Turn on all light at max brightness
#
# https://www.home-assistant.io/integrations/deconz/#remote-control-devices
#

alias: salle_de_bain_remote_long
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
      event: 1003
action:
  - service: scene.turn_on
    entity_id: scene.salle_de_bain_on
