---
# presence_leaving
#
# All actions triggered when presence --> leaving
#

alias: "presence_leaving"
trigger:
  - platform: state
    entity_id: input_select.presence
    to: "leaving"
action:
  - service: homeassistant.turn_off
    entity_id: group.presence_leaving_off
  - service: homeassistant.turn_on
    entity_id: group.presence_leaving_on
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.alarme
