---
# When toilets occupied
# --> Store lights for restoring
#
# The delay prevent storing the current state during a transition
# (if you switch/bounce the sensor twice during transition)
#
alias: "toilets_lights_on_before"
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_toilets
    to: "on"
max_exceeded: silent # Delay is intented, single run is what we want
action:
  - service: scene.create
    data:
      scene_id: bathroom_before
      snapshot_entities:
        - light.salle_de_bain_1
        - light.salle_de_bain_2
        - light.salle_de_bain_3
        - light.salle_de_bain_4
  - delay:
      seconds: 15
