---
# Nothing Playing on Living TV for a while --> Activity = undetermined
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_activity_undetermined"
trigger:
  - platform: state
    entity_id: media_player.nvidia_shield_cast
    from: "playing"
    for:
      minutes: 10
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.activity
      option: "undetermined"
