---
# Playing on Living TV for a while --> Activity = entertain_in_living
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_activity_entertain_in_living"
trigger:
  - platform: state
    entity_id: media_player.nvidia_shield_cast
    to: "playing"
    for:
      minutes: 3
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.activity
      option: "entertain_in_living"
