# Re-enable any unstoppable switch as soon as its turned off
#
alias: switch_unstoppable
trigger:
  - platform: state
    entity_id:
      - switch.living_switch_left
      - switch.hall_switch_left
      - switch.hall_switch_right
      - switch.bar_switch_left
      - switch.bar_switch_right
      - switch.chambre_switch_left
      - switch.chambre_switch_right

action:
  - service: home_assistant.turn_on
    target:
      entity_id: "{{ trigger.entity_id }}"
