---
# Notify when a new UberEats order is made
#
# https://gist.github.com/donkawechico/30399f34fa88f0c560f9eb0c756d2efa

alias: ubereats_notify_new
trigger:
  - entity_id:
      - sensor.uber_eats_new_eta
    platform: state
condition: []
action:
  - service: script.tts_processing
    data_template:
      message: >
        {{ [
        "Wouhou! Une commande UberEats chez {{ states.sensor.uber_eats_order.attributes.restaurant_name }} est en cours, elle est attendue dans {{ states.sensor.uber_eats_minutes_eta  }} minutes.",
        "Génial! Une commande UberEats chez {{ states.sensor.uber_eats_order.attributes.restaurant_name }} est en cours, elle est attendue dans {{ states.sensor.uber_eats_minutes_eta  }} minutes.",
        "A table! Une commande UberEats chez {{ states.sensor.uber_eats_order.attributes.restaurant_name }} est en cours, elle est attendue dans {{ states.sensor.uber_eats_minutes_eta  }} minutes.",
        "On va manger! Une commande UberEats chez {{ states.sensor.uber_eats_order.attributes.restaurant_name }} est en cours, elle est attendue dans {{ states.sensor.uber_eats_minutes_eta  }} minutes.",
        ] |random }}
mode: single
