blueprint:
  name: Aqara Double-Gang
  description: |
    Allow control of an Aqara Double-Gang Switch
  domain: automation
  input:
    switch:
      name: Action for Switch
      description: Action sensor of the  Aqara Wireless Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    press_left_single:
      name: Single Left button press
      description: Action to run on single left button press
      default: []
      selector:
        action: {}
    press_right_single:
      name: Single Right button press
      description: Action to run on single right button press
      default: []
      selector:
        action: {}
    press_left_hold:
      name: Left Button hold
      description: Action to run on hold
      default: []
      selector:
        action: {}
    press_right_hold:
      name: Right Button hold
      description: Action to run on hold
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "switch"
    attribute: action
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'left_single' }}"
        sequence: !input "press_left_single"
      - conditions:
          - "{{ command == 'right_single' }}"
        sequence: !input "press_right_single"
      - conditions:
          - "{{ command == 'left_hold' }}"
        sequence: !input "press_left_hold"
      - conditions:
          - "{{ command == 'right_hold' }}"
        sequence: !input "press_right_hold"
