blueprint:
  name: TRÅDFRI Switch
  description: |
    Allow control of an IKEA TRÅDFRI Switch
  domain: automation
  input:
    remote:
      name: Action for Remote
      description: Action of the  IKEA TRÅDFRI Remote
      selector:
        entity:
          domain: sensor
          integration: mqtt
    my_entity:
      name: Entity
      description: Entity that will be toggled by this Switch
      selector:
        target:
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    attribute: action

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'on' }}"
        sequence:
          - service: home_assistant.turn_on
            target: !input my_entity
      - conditions:
          - "{{ command == 'off' }}"
        sequence:
          - service: home_assistant.turn_off
            target: !input my_entity
