---
# Period set to "waking_up"
#     —> Create event in calendar
#

alias: "waking_up"
trigger:
  - platform: state
    entity_id: input_select.period
    to: "waking_up"
action:
  - service: google.add_event
    data_template:
      calendar_id: !secret calendar_activity_id
      summary: "#WokeUp"
      description: "Woke up at {{ now().strftime('%H:%M:%S') }}"
      start_date_time: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
      end_date_time: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
