---
# Loading both static automation from this repo
# + UI-generated Automation from root yaml file
#
# https://www.home-assistant.io/docs/automation/
#
automation: !include ../../automations.yaml
automation split: !include_dir_list ../../automations
