apiVersion: v1
kind: Service
metadata:
  name: home-assistant-staging
  labels:
    app: home-assistant-staging
spec:
  selector:
    app: home-assistant-staging
  ports:
    - protocol: TCP
      port: 8123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant-staging
  name: home-assistant-staging
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-assistant-staging
  template:
    metadata:
      labels:
        app: home-assistant-staging
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          name: home-assistant-staging
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 8123
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: 8123
              scheme: HTTP
      restartPolicy: Always

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home-assistant-staging
spec:
  rules:
    - host: staging.smarthome.thomashermine.be
      http:
        paths:
          - backend:
              serviceName: home-assistant-staging
              servicePort: 8123
