- platform: statistics
  name: bathroom_humidity_statistics
  entity_id: sensor.bathroom_humidity
  sampling_size: 2

- platform: template
  sensors:
    bathroom_humidity_change_rate:
      unit_of_measurement: "percent"
      value_template: "{{ states.sensor.douche_temperature_humidity.attributes.change_rate }}"
