---
# Stats for Motion Sensors
#
# https://www.home-assistant.io/integrations/statistics/

- platform: statistics
  name: kitchen_motion_stats
  entity_id: binary_sensor.kitchen_motion
  sampling_size: 60
  max_age:
    seconds: 60
