- platform: template
  sensors:
    # Helper — Greetings
    # ==========================================================================
    greetings:
      value_template: >-
        {% if is_state("input_select.presence", "coming_home") -%}
        Bon retour à la maison.
        {% elif is_state("input_select.period", "early_morning") %}
        Bon réveil.
        {% elif is_state("input_select.period", "waking_up") %}
        Bon réveil.
        {% elif is_state("input_select.period", "afternoon") %}
        Bonne aprés-midi.
        {% elif is_state("input_select.period", "evening") %}
        Bonne soirée.
        {% elif is_state("input_select.period", "late_evening") %}
        Bonne soirée.
        {% elif is_state("input_select.period", "fallig_asleep") %}
        Bonne nuit.
        {% else %}
        Bonne journée.
        {% endif %}

    # Helper — Room Temperature
    # ==========================================================================
    #  Climate On :
    #   Il fait 18°, bientôt 20.
    #  Climate Off :
    #   Il fait 20°.

    summary_temperature_room_chambre:
      value_template: >-
        Il fait **{{states.sensor.chambre_temperature.state| int}}°**{% if states.sensor.chambre_heating.state | int > 0 %}, bientôt **{{states.climate.chambre.attributes.temperature | int }}°**{% endif %}.
    summary_temperature_room_living:
      value_template: >-
        Il fait **{{states.sensor.living_temperature.state| int}}°**{% if states.sensor.living_heating.state | int > 0 %}, bientôt **{{states.climate.living.attributes.temperature | int }}°**{% endif %}.

    summary_temperature_room_cuisine: # TODO: Add temperature for cuisine, climate for cuisine
      value_template: >-
        Il fait **{{states.sensor.living_temperature.state| int}}°**{% if states.sensor.living_heating.state | int > 0 %}, bientôt **{{states.climate.living.attributes.temperature | int }}°**{% endif %}.

    summary_temperature_room_salle_de_bain:
      value_template: >-
        Il fait **{{states.sensor.salle_de_bain_temperature.state| int}}°**{% if states.sensor.salle_de_bain_heating.state | int > 0 %}, bientôt **{{states.climate.salle_de_bain.attributes.temperature | int }}°**{% endif %}.

    summary_temperature_home:
      value_template: >-
        Il fait **{{states.sensor.living_temperature.state| int}}°** à la maison, **{{states.weather.andenne_81.attributes.temperature}}°** dehors.

    # Summary - Home
    #  <summary_temperature_home> <major_conditions> <single_condition> <greeting>
    # ==========================================================================
    #
    #  Il fait 20° à la maison, 10° dehors. L'alarme est active. La porte d'entrée est ouverte.
    #
    #  Il fait 20° à la maison, 10° dehors. Quelqu'un prend une douche. Bonne journée!
    #  Il fait 20° à la maison, 10° dehors. La hotte fonctionne.  Bonne journée!
    #  Il fait 20° à la maison, 10° dehors. L'aspirateur fonctionne.  Bonne journée!
    #
    # TODO: Add following cases:
    #
    #  Il fait 20° à la maison, 10° dehors. L'aspirateur à fonctionné à 18h00. Bonne journée!
    #  Il fait 20° à la maison, 10° dehors. Vous regardez Breaking Bad. Bonne journée!
    #  Il fait 20° à la maison, 10° dehors. Vous écoutez La Danse des Etoiles de Fakear. Bonne journée!
    #
    #
    #  Il fait 20° à la maison, 10° dehors. La chaudière fonctionne.  Bonne journée!

    # TODO: Check hygie state when cleaning
    summary_home:
      value_template: >-
        {{states.sensor.summary_temperature_home.state}}
        {% if is_state("binary_sensor.hall_door", "on") %}
        La **porte d'entrée** est ouverte.
        {% endif %}
        {% if is_state("switch.hotte", "on") %}
        La **hotte** fonctionne.
        {% elif is_state("vacuum.hygie", "cleaning") %}
        **L'aspirateur** fonctionne.
        {% elif is_state("switch.chaudiere", "on") %}
        La **chaudière** fonctionne
        {% endif %}
    # Summary - Living
    #  <summary_temperature_room> <condition>
    # ==========================================================================
    #
    #  Il fait 20°, bientôt 22°. Le balcon est ouvert. Vous regardez Breaking Bad.
    #
    #  Il fait 20°, bientôt 22°. Vous regardez Breaking Bad.
    #  Il fait 20°, bientôt 22°. Les lampes sont allumées.

    summary_living:
      value_template: >-
        {{states.sensor.summary_temperature_room_living.state}}

    # Summary - Cuisine
    #  <summary_temperature_room> <condition>
    # ==========================================================================
    #
    #  Il fait 20°. La hotte fonctionne
    #  Il fait 20°. Le robinet coule
    #  Il fait 20°. Le lave-vaiselle doit être vidé.
    #  Il fait 20°. Le lave-vaiselle fonctionne.
    #  Il fait 20°. Les lampes sont allumées.

    summary_cuisine:
      value_template: >-
        {{states.sensor.summary_temperature_room_cuisine.state}}

    # Summary - Salle de Bain
    #  <summary_temperature_room> <condition> <major_condition>
    # ==========================================================================
    #
    #  Il fait 20°. Vous écoutez Fakear dans la salle de bain.
    #  Il fait 20°. La salle de bain est occupée.
    #
    #  Il fait 20°. La salle de bain est occupée. L'aération fonctionne.

    summary_salle_de_bain:
      value_template: >-
        {{states.sensor.summary_temperature_room_salle_de_bain.state}}
        {% if is_state("switch.extracteur_d_air_salle_de_bain", "on") %}
        L'aération fonctionne.
        {% endif %}

    # Summary - Chambre
    #  <summary_temperature_room> <major_conditions>
    # ==========================================================================
    #
    #  Il fait 20°. La terasse est ouverte. Le ventilateur fonctionne. Les lampes sont allumées.
    # Summary - Hall & Buanderie

    summary_chambre:
      value_template: >-
        {{states.sensor.summary_temperature_room_chambre.state}}
        {% if is_state("binary_sensor.terrace_door", "on") %}
        La porte de la terrasse est ouverte.
        {% endif %}
    # Summary - Hall & Buanderie
    #  <summary_temperature_room> <major_conditions>
    # ==========================================================================
    #
    #  Il fait 20°. La porte d'entrée est ouverte. La macine à lessiver fonctionne. L'extracteur d'air de la buanderie fonctionne.
    #

    summary_hall:
      value_template: >-
        {{states.sensor.summary_temperature_room_living.state}}
        {% if is_state("switch.extracteur_d_air_buanderie", "on") %}
        L'aération de la buanderie fonctionne.
        {% endif %}
