---
# Nearest person more than Xkm away --> on_trip
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_presence_on_trip"
trigger:
  - platform: numeric_state
    entity_id: proximity.home
    above: 80
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.persons
      state: "not_home"
    - condition: state
      entity_id: input_boolean.guests
      state: "off"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: on_trip
