---
# Any person to Home --> Approaching
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_presence_approaching"
trigger:
  - platform: state
    entity_id: group.persons
    to: "home"
  - platform: numeric_state
    entity_id: proximity.home
    below: 1
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_select.presence
      state: "away"
    - condition: state
      entity_id: input_select.presence
      state: "on_trip"
    - condition: state
      entity_id: input_select.presence
      state: "back_from_trip"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: "approaching"
