---
# Everybody away --> Leaving
#
# https://www.home-assistant.io/integrations/input_select/
#

alias: "input_select_presence_leaving"
trigger:
  - platform: state
    entity_id: group.persons
    from: "home"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: "input_boolean.guests"
      state: "off"
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: leaving
