# cafetiere_timer_off
# Turn off cafetiere not from automation --> Turn off loop
#
# Cafetiere auto-shutdown (switch jumps to off) if left on for more than 30mn
# (some bullshit EU regulations stuff, like I'd care about fires)
# In that case, we loose control of it : the power outlet can't do anything
# we need to press the button on the appliance.
# A timer allows us to avoid that case.
# Cause we don't like pressing buttons.
# We have big fingers
#
# https://www.home-assistant.io/integrations/input_boolean/
#
alias: cafetiere_timer_off_loop
trigger:
  - platform: state
    entity_id: switch.cafetiere
    to: "off"
    for:
      seconds: 10 # Needs to be higher than value in cafetiere_timer_end_loop
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.cafetiere_loop
