---
# Actions when period is set to "early_morning"
#

alias: "early_morning"
trigger:
  - platform: state
    entity_id: input_select.period
    to: "early_morning"
action:
  # Start heating
  - service: script.climate_home
  - service: script.climate_salle_de_bain
