---
# When no motion in salle_de_bain for a while
# --> Turn off lights
#
alias: "motion_bathroom_off"
trigger:
  - platform: state
    entity_id: binary_sensor.salle_de_bain_door_occupancy
    to: "off"
    for:
      minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.salle_de_bain_door_occupancy
      state: "off"
      for:
        minutes: 2
action:
  service: homeassistant.turn_off
  entity_id: light.salle_de_bain
