---
# When no motion in salle_de_bain for a while
# --> Turn off lights
#
alias: "motion_bathroom_off"
trigger:
  - platform: state
    entity_id:
      - binary_sensor.salle_de_bain_door_occupancy
      - binary_sensor.salle_de_bain_motion_shower_occupancy
    to: "off"
    for:
      minutes: 5
condition:
  condition: and
  conditions:
    - condition: state
      entity_id:
        - binary_sensor.salle_de_bain_door_occupancy
      state: "off"
      for:
        minutes: 5
    - condition: state
      entity_id:
        - binary_sensor.salle_de_bain_motion_shower_occupancy
      state: "off"
      for:
        minutes: 5
action:
  service: homeassistant.turn_off
  entity_id: light.salle_de_bain
