---
# When motion in bathroom
# --> Turn on light
#
alias: "motion_bathroom_on"
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion
    to: "on"
  - platform: state
    entity_id: binary_sensor.bathroom_motio_floating
    to: "on"
action:
  service: homeassistant.turn_on
  entity_id: light.salle_de_bain
