---
# climate_hack_24
# Hack while waiting for the plumber... avoid "knock-knock" noise when
# valve is at oscilation position
#
# https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger
#

alias: climate_hack_24
trigger:
  - platform: numeric_state
    entity_id: climate.bureau, climate.chambre, climate.living
    attribute: temperature
    above: 23.9
    below: 24.1
    for:
      seconds: 30
action:
  - service: climate.set_temperature
    target:
      # Turn off whichever entity triggered the automation.
      entity_id: "{{ trigger.entity_id }}"
    data:
      temperature: 22
